services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.9-management
    networks:
      - rabbitmq-net
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - 4369:4369
      - 5671:5671
      - 5672:5672
      - 15672:15672

  app:
    build:
      context: .
    container_name: springboot-rabbitmq-app
    networks:
      - rabbitmq-net
    ports:
      - 8080:8080
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
    depends_on:
      - rabbitmq
    restart: always

networks:
  rabbitmq-net:
    name: rabbitmq-net